### ISSUE TITLE
'DeezerSongChoice' object has no attribute 'path'

### ISSUE THREAD

**Issue by Rawrior** [SEbbaDK/sonica#81]
Exception is raised in grpc lib, but intersects with our code here
```
File "/home/simon/Documents/personal-projects/sonica/discord/sonica-discord.py", line 94, in choose
    daemon.Choose(Search.Choice( possibility_id = id, add_to_top = play_next ))
```

<details>
    <summary>Full stacktrace</summary>

```
Ignoring exception in command choose:
Traceback (most recent call last):
  File "/home/simon/Documents/personal-projects/sonica/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/simon/Documents/personal-projects/sonica/discord/sonica-discord.py", line 94, in choose
    daemon.Choose(Search.Choice( possibility_id = id, add_to_top = play_next ))
  File "/home/simon/Documents/personal-projects/sonica/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/simon/Documents/personal-projects/sonica/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'DeezerSongChoice' object has no attribute 'path'"
	debug_error_string = "{"created":"@1645183550.985028834","description":"Error received from peer ipv6:[::1]:7700","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Exception calling application: 'DeezerSongChoice' object has no attribute 'path'","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simon/Documents/personal-projects/sonica/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/simon/Documents/personal-projects/sonica/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/simon/Documents/personal-projects/sonica/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: _InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'DeezerSongChoice' object has no attribute 'path'"
	debug_error_string = "{"created":"@1645183550.985028834","description":"Error received from peer ipv6:[::1]:7700","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Exception calling application: 'DeezerSongChoice' object has no attribute 'path'","grpc_status":2}"
```
</details>

**Comment by SEbbaDK** [comment]
My guess is that it's line 40 of `deezer-engine.py`. Something might have changed in the way `Downloader` works to generate different events.

```python
    @dataclass
    class DeezerSongChoice(SongChoice):
        dz: Deezer
        link: str
        dir: str

        def choose(self):
            downloader = deemix.generateDownloadObject(
                self.dz,
                self.link,
                TrackFormats.MP3_320
            )
            self.dl = Downloader(self.dz, downloader, {
                **deemix.settings.DEFAULTS,
                'downloadLocation': self.dir,
            }, listener = self).start()
            return self.path

        def send(self, kind, message):
            if kind != 'updateQueue':
                return
            if 'downloaded' in message and message['downloaded']:
                self.path = message['downloadPath']
```

**Comment by SEbbaDK** [comment]
More specifically here https://github.com/SEbbaDK/sonica/blob/2dbb9a3db30ebb85d4a78f519c71f1bd2a635e72/daemon/engines/deezer_engine.py#L46

**Comment by SEbbaDK** [comment]
The problem is that free deezer accounts can't do 320bps MP3 anymore
